@startuml SpaceCar

class Juego{
    + Comenzar()
    - Terminar()
}
class Jugador
class Habilidad

class Velocidad{
    + Alta()
    + Baja
}
class Manejo

class PowerUp
class Item

class Carro{
    + Ariiba()
    + Abajo()
}
class Obstaculo{
    + Señal()
    + Punto()
}
class Pista

class Nino

Juego "1" *-- "1" Jugador
Jugador "1" o-- "1" Carro
Carro "1" *-- "1" Habilidad
Carro "1" *-- "1" Control

Carro --|> Item
PowerUp --|> Item
Obstaculo --|> Item

PowerUp --|> Habilidad
Manejo --|> Habilidad
Velocidad --|> Habilidad

Pista -- Obstaculo


@enduml
